require "config.launch"
require "config.options"
require "config.keymaps"
require "config.autocmds"

spec "plugins.alpha"
spec "plugins.autopairs"
spec "plugins.barbar"
spec "plugins.breadcrumbs"
spec "plugins.bufdelete"
spec "plugins.cmp"
spec "plugins.colorscheme"
spec "plugins.devicons"
spec "plugins.diffview"
-- spec "plugins.grammarous"
spec "plugins.flutter-tools"
spec "plugins.illuminate"
spec "plugins.indentline"
spec "plugins.lspconfig"
spec "plugins.lualine"
spec "plugins.mason"
spec "plugins.navic"
spec "plugins.neogit"
spec "plugins.netrw"
spec "plugins.notify"
spec "plugins.nvimtree"
-- spec "plugins.peek"
spec "plugins.project"
spec "plugins.schemastore"
spec "plugins.telescope"
spec "plugins.telescope-tabs"
spec "plugins.toggleterm"
spec "plugins.treesitter"

require "plugins.lazy"
